version: '3.9'

services:
  postgres:
    container_name: ${DB_PG_HOST}
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PG_PORT}:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_PG_USERNAME}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
      POSTGRES_DB: ${DB_PG_NAME}
    volumes:
      - ./volumes/pg_database:/var/lib/postgresql/data