version: '3.9'

services:
  server:
    build: 
      context: .
      target: production
    container_name: good-news-everyone-server
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - app

  postgres:
    container_name: ${DB_PG_HOST}
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PG_PORT}:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_PG_USERNAME}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
      POSTGRES_DB: ${DB_PG_NAME}
    volumes:
      - ./volumes/pg_database:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    driver: bridge