import { XML_ATTRIBUTE_NAME_PREFIX } from '../@constants/attribute-prefix';

export enum PREFIXED_ATTRIBUTES {
  ENCODING = `${XML_ATTRIBUTE_NAME_PREFIX}encoding`,
  VERSION = `${XML_ATTRIBUTE_NAME_PREFIX}version`,
  XMLNS_ATOM = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:atom`,
  XMLNS_CONTENT = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:content`,
  XMLNS_DC = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:dc`,
  XMLNS_MEDIA = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:media`,
  XMLNS_NYT = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:nyt`,
  XMLNS_STR = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:str`,
  XMLNS_WSJ = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:wsj`,
  XMLNS_DJ = `${XML_ATTRIBUTE_NAME_PREFIX}xmlns:dj`,
  HREF = `${XML_ATTRIBUTE_NAME_PREFIX}href`,
  REL = `${XML_ATTRIBUTE_NAME_PREFIX}rel`,
  TYPE = `${XML_ATTRIBUTE_NAME_PREFIX}type`,
  HEIGHT = `${XML_ATTRIBUTE_NAME_PREFIX}height`,
  MEDIUM = `${XML_ATTRIBUTE_NAME_PREFIX}medium`,
  URL = `${XML_ATTRIBUTE_NAME_PREFIX}url`,
  WIDTH = `${XML_ATTRIBUTE_NAME_PREFIX}width`,
  IS_PERMA_LINK = `${XML_ATTRIBUTE_NAME_PREFIX}isPermaLink`,
  DOMAIN = `${XML_ATTRIBUTE_NAME_PREFIX}isPermaLink`,
}
